import HeaderDeslogado from "@/components/HeaderDeslogado";
import "../globals.css";

export const metadata = {
  title: 'Login',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <HeaderDeslogado />
        {children}
      </body>
    </html>
  )
}
